theme = "karokari"
languageCode = "en-us"
baseURL = "/"
title = "Antroy Tech"

[params]

  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Custom copyright - optional
  copyright = "Copyright © 2022 - Antroy Tech · All Rights Reserved."
  favicon = "/img/favicon.ico"
  
[params.homepage]
  description = "Antroy Tech adalah Tempat kolaborasi teknologi dengan semangat open source. Belajar, berbagi, dan berinovasi bersama di era digital yang inklusif!"
  logo = "/img/logo.png"
  light_papua_island = "/svg/papuaisland-light.svg"
  dark_papua_island = "/svg/papuaisland-dark.svg"
  
[[menu.main]]
  name = "About"
  url = "/about"
  
[[menu.main]]
  name = "Support"
  url = "/support"
  
  